AllCops:
  Exclude:
    - config/initializers/*
    - db/schema.rb
    - spec/spec_helper.rb
    - bin/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
