inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - config/initializers/*
    - db/schema.rb
    - lib/vcap_services.rb
    - spec/spec_helper.rb
    - bin/*
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20
