inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - Gemfile
  Exclude:
    - db/schema.rb
    - spec/spec_helper.rb
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/GuardClause:
  Enabled: false
