version: '3'
services:
  web:
    build: .
    # The pidfile often ends up not being deleted on shutdown, there's no reason to
    # keep it around in an ephemeral Docker container anyway, so set it to /dev/null
    command: bundle exec rails s -p 4000 -b '0.0.0.0' -P /dev/null
    env_file: .env
    volumes:
      # Volume set to `delegated` to improve performance (container FS authoritative)
      - .:/workspace:delegated
    ports:
      - "4000:4000"
