version: '3'
services:
  redis_cache:
    image: redis
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    env_file: .env
    environment:
      REDIS_URL: "redis://redis_cache"
    volumes:
      # Volume set to `delegated` to improve performance (container FS authoritative)
      - .:/workspace:delegated
    ports:
      - "4000:4000"
    depends_on:
      - redis_cache
