version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/digital-workspace
    steps:
      - checkout
      - run: cp .circleci/env .env
      - run: docker-compose up -d
      - run: docker-compose run web bundle exec rake ci
